# Generated by Django 6.0.2 on 2026-05-21 17:16

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_tipo_cliente_alter_cliente_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaGastosEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3E9FA2', max_length=7)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaGastosOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('SOLICITUD_PAGO', 'Solicitud de pago'), ('SOLICITUD_FACTURAS', 'Solicitud de facturas'), ('SOLICITUD_CUENTA_GASTOS', 'Solicitud de cuenta de gastos'), ('FACTURA_ANTICIPO', 'Factura por Anticipo'), ('FLETE_ESPERA_PAGO', 'Flete en espera de pago'), ('EN_PROCESO', 'En Proceso'), ('VOBO_ANGIE', 'VoBo Angie'), ('APROBADAS', 'Aprobadas'), ('SOLICITADAS_GEO', 'Solicitadas a Geo'), ('POR_ENVIAR_CLIENTE', 'Por enviar al cliente'), ('DEVOLUCION', 'Devolución'), ('COBRANZA', 'Cobranza'), ('COMPLEMENTO_PAGO', 'Complemento de pago'), ('DEUDORES_MOROSOS', 'Deudores Morosos'), ('COMERCIALIZADORAS', 'Comercializadoras')], default='SOLICITUD_PAGO', max_length=50)),
                ('prioridad', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignados', models.ManyToManyField(blank=True, related_name='cuentas_gastos_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_gastos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_gastos_creadas', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='cuentas_gastos', to='cuenta_gastos.cuentagastosetiqueta')),
                ('opciones', models.ManyToManyField(blank=True, related_name='cuentas_gastos', to='cuenta_gastos.cuentagastosopcion')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaGastosArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='uploads'), upload_to='cuenta_gastos/archivos/%Y/%m/')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuenta_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='cuenta_gastos.cuentagastos')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaGastosComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuenta_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cuenta_gastos.cuentagastos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaGastosEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cuenta_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='cuenta_gastos.cuentagastos')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
