# Generated by Django 6.0.2 on 2026-07-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_gastos', '0001_initial'),
        ('operaciones', '0003_operacion_referencia_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentagastos',
            name='operacion_origen',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_gastos_generada', to='operaciones.operacion'),
        ),
    ]
