# Generated by Django 6.0.2 on 2026-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_gastos', '0002_cuentagastos_operacion_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentagastos',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD_PAGO', 'Solicitud de pago'), ('SOLICITUD_FACTURAS', 'Solicitud de facturas'), ('SOLICITUD_CUENTA_GASTOS', 'Solicitud de cuenta de agencia aduanal'), ('FACTURA_ANTICIPO', 'Factura por Anticipo'), ('FLETE_ESPERA_PAGO', 'Flete en espera de pago'), ('EN_PROCESO', 'En Proceso'), ('VOBO_ANGIE', 'VoBo Angie'), ('APROBADAS', 'Aprobadas'), ('SOLICITADAS_GEO', 'Solicitadas a Geo'), ('POR_ENVIAR_CLIENTE', 'Por enviar al cliente'), ('DEVOLUCION', 'Devolución'), ('COBRANZA', 'Cobranza'), ('COMPLEMENTO_PAGO', 'Complemento de pago'), ('DEUDORES_MOROSOS', 'Deudores Morosos'), ('COMERCIALIZADORAS', 'Comercializadoras')], default='SOLICITUD_PAGO', max_length=50),
        ),
    ]
