# Generated by Django 6.0.2 on 2026-08-03 21:27

import cuenta_gastos.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_gastos', '0003_alter_cuentagastos_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='uploads'), upload_to=cuenta_gastos.models.documento_repositorio_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_repositorio_cuenta_gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida', '-id'],
            },
        ),
    ]
