# Generated by Django 6.0.2 on 2026-08-19 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_gastos', '0007_cuentagastos_eliminado_en_cuentagastos_eliminado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorepositorio',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documentorepositorio',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_repositorio_cuenta_gastos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
