# Generated by Django 6.0.2 on 2026-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_gastos', '0008_documentorepositorio_eliminado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentagastoscolumna',
            name='color_fondo',
            field=models.CharField(default='#F8F9FA', max_length=7, verbose_name='Color de fondo'),
        ),
    ]
