# Generated by Django 6.0.2 on 2026-09-28 18:35

import django.db.models.deletion
from django.db import migrations, models

def crear_columna_devolucion(apps, schema_editor):
    Columna = apps.get_model('cuenta_gastos', 'CuentaGastosColumna')
    Columna.objects.get_or_create(
        codigo='DEVOLUCION_A_GARANTIAS',
        defaults={'nombre': 'Devolución a garantías', 'orden': (Columna.objects.order_by('-orden').values_list('orden', flat=True).first() or 0) + 1, 'activa': True},
    )
    Columna.objects.filter(codigo="DEVOLUCION_A_GARANTIAS").update(nombre="Devoluci" + chr(243) + "n a garant" + chr(237) + "as")


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_gastos', '0009_cuentagastoscolumna_color_fondo'),
        ('garantias', '0013_garantia_operacion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentagastos',
            name='agencia_aduanal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(crear_columna_devolucion, migrations.RunPython.noop),
        migrations.AddField(
            model_name='cuentagastos',
            name='garantia_origen',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_gastos_generada', to='garantias.garantia'),
        ),
    ]
