# Generated by ChatGPT on 2026-05-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelCotizacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("cliente", models.CharField(max_length=255)),
                ("prioridad", models.CharField(choices=[("BAJA", "Baja"), ("MEDIA", "Media"), ("ALTA", "Alta")], default="MEDIA", max_length=10)),
                ("estado", models.CharField(choices=[("REQUERIMIENTO", "Requerimiento"), ("EN_PROGRESO", "En progreso"), ("ENVIADA", "Enviada")], default="REQUERIMIENTO", max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("asignados", models.ManyToManyField(blank=True, related_name="panel_cotizaciones_asignadas", to=settings.AUTH_USER_MODEL)),
                ("creado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="panel_cotizaciones_creadas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PanelCotizacionComentario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("cotizacion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comentarios", to="panel_cotizaciones.panelcotizacion")),
                ("creado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="panel_cotizacion_comentarios", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]

