# Generated by Django 6.0.2 on 2026-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelcotizacion',
            name='cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='panelcotizacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='panelcotizacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
