# Generated by Django 6.0.2 on 2026-05-15 20:26

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_cotizaciones', '0002_alter_panelcotizacion_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelCotizacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='uploads'), upload_to='panel_cotizaciones/archivos/%Y/%m/')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='panel_cotizaciones.panelcotizacion')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_cotizacion_archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PanelCotizacionEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='panel_cotizaciones.panelcotizacion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_cotizacion_enlaces_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
