# Generated by Django 6.0.2 on 2026-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_cotizaciones', '0003_panelcotizacionarchivo_panelcotizacionenlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelCotizacionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3E9FA2', max_length=7)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='panelcotizacion',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='cotizaciones', to='panel_cotizaciones.panelcotizacionetiqueta'),
        ),
    ]
