# Generated by Django 6.0.2 on 2026-08-10 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_cotizaciones', '0007_panelcotizacion_eliminado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelCotizacionElementoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('completado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_accion', to='panel_cotizaciones.panelcotizacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
