from django.urls import path
from . import views

app_name = "cuenta_gastos"

urlpatterns = [

    path(
        "",
        views.panel_cuenta_gastos,
        name="panel_cuenta_gastos"
    ),
    path(
        "repositorio/",
        views.repositorio_listado,
        name="repositorio_listado",
    ),
    path(
        "repositorio/subir/",
        views.repositorio_subir,
        name="repositorio_subir",
    ),
    path(
        "repositorio/<int:pk>/ver/",
        views.repositorio_visualizar,
        name="repositorio_visualizar",
    ),
    path(
        "repositorio/<int:pk>/descargar/",
        views.repositorio_descargar,
        name="repositorio_descargar",
    ),

    path(
        "crear/",
        views.crear_cuenta_gastos,
        name="crear_cuenta_gastos"
    ),
    path(
        "columnas/crear/",
        views.columna_crear,
        name="columna_crear"
    ),
    path(
        "columnas/reordenar/",
        views.columna_reordenar,
        name="columna_reordenar"
    ),
    path(
        "columnas/<int:pk>/editar/",
        views.columna_editar,
        name="columna_editar"
    ),
    path(
        "columnas/<int:pk>/eliminar/",
        views.columna_eliminar,
        name="columna_eliminar"
    ),
    path(
        "columnas/<int:columna_id>/pegar/",
        views.tarjeta_pegar,
        name="tarjeta_pegar"
    ),
    path(
        "crear-inline/",
        views.crear_cuenta_gastos_inline,
        name="crear_cuenta_gastos_inline"
    ),
    path(
        "nueva/inline/formulario/",
        views.formulario_cuenta_gastos_inline,
        name="formulario_cuenta_gastos_inline",
    ),
    path(
        "columna/<str:codigo>/tarjetas/",
        views.tarjetas_columna,
        name="tarjetas_columna",
    ),

    path(
        "detalle/<int:pk>/",
        views.detalle_cuenta_gastos,
        name="detalle_cuenta_gastos"
    ),
    path(
        "<int:pk>/inline-update/",
        views.actualizar_cuenta_inline,
        name="actualizar_cuenta_inline"
    ),
    path(
        "<int:pk>/inline-editor/",
        views.editor_cuenta_inline,
        name="editor_cuenta_inline",
    ),

    path(
        "<int:pk>/mover/",
        views.mover_cuenta_gastos,
        name="mover_cuenta_gastos"
    ),

    path(
        "editar/<int:pk>/",
        views.editar_cuenta,
        name="editar_cuenta"
    ),
    path(
        "opcion/crear/",
        views.crear_opcion,
        name="crear_opcion"
    ),
    path(
        "etiqueta/crear/",
        views.crear_etiqueta,
        name="crear_etiqueta"
    ),
    path(
        "etiqueta/<int:etiqueta_id>/eliminar/",
        views.eliminar_etiqueta,
        name="eliminar_etiqueta"
    ),
    path(
        "<int:pk>/etiquetas/",
        views.actualizar_etiquetas_cuenta,
        name="actualizar_etiquetas_cuenta"
    ),
    path(
        "<int:pk>/etiquetas/crear/",
        views.crear_etiqueta_cuenta,
        name="crear_etiqueta_cuenta"
    ),
    path(
        "<int:pk>/etiquetas/<int:etiqueta_id>/quitar/",
        views.quitar_etiqueta_cuenta,
        name="quitar_etiqueta_cuenta"
    ),
    path(
        "<int:pk>/opciones/",
        views.actualizar_opciones_cuenta,
        name="actualizar_opciones_cuenta"
    ),
    path(
        "<int:pk>/opciones/crear/",
        views.crear_opcion_cuenta,
        name="crear_opcion_cuenta"
    ),
    path(
        "<int:pk>/opciones/<int:opcion_id>/quitar/",
        views.quitar_opcion_cuenta,
        name="quitar_opcion_cuenta"
    ),
    path(
        "<int:pk>/comentario/",
        views.agregar_comentario,
        name="agregar_comentario"
    ),
    path(
        "<int:pk>/archivo/",
        views.agregar_archivo,
        name="agregar_archivo"
    ),
    path(
        "<int:pk>/archivo/eliminar/",
        views.eliminar_archivo,
        name="eliminar_archivo"
    ),
    path(
        "<int:pk>/enlace/",
        views.agregar_enlace,
        name="agregar_enlace"
    ),
    path(
        "<int:pk>/enlace/eliminar/",
        views.eliminar_enlace,
        name="eliminar_enlace"
    ),
    path(
        "<int:pk>/eliminar/",
        views.eliminar_cuenta,
        name="eliminar_cuenta"
    ),
]
