# Generated by Django 6.0.3 on 2026-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20),
        ),
    ]
