# Generated by Django 6.0.3 on 2026-05-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def mapear_estados(apps, schema_editor):
    Garantia = apps.get_model("garantias", "Garantia")
    mapping = {
        "CREADA": "SOLICITUD_NAVIERA",
        "PRESENTADA": "EN_PROCESO",
        "RESUELTA": "DEVOLUCION_CLIENTE",
    }
    for old, new in mapping.items():
        Garantia.objects.filter(estado=old).update(estado=new)


class Migration(migrations.Migration):

    dependencies = [
        ("garantias", "0002_garantia_prioridad"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarantiaArchivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to="garantias/archivos/%Y/%m/")),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("garantia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="archivos", to="garantias.garantia")),
                ("subido_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GarantiaEnlace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=1000)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("creado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("garantia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enlaces", to="garantias.garantia")),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddField(
            model_name="garantia",
            name="asignados",
            field=models.ManyToManyField(blank=True, related_name="garantias_asignadas", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="garantia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SOLICITUD_NAVIERA", "Solicitud a naviera"),
                    ("EN_PROCESO", "En proceso"),
                    ("PAGO_NAVIERA_ZAHA", "Pago naviera a zaha"),
                    ("DEVOLUCION_CLIENTE", "Devolución a cliente"),
                ],
                default="SOLICITUD_NAVIERA",
                max_length=20,
            ),
        ),
        migrations.RunPython(mapear_estados, migrations.RunPython.noop),
    ]
