# Generated by Django 6.0.2 on 2026-05-14 20:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0003_estados_asignados_archivos_enlaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantiaarchivo',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='uploads'), upload_to='garantias/archivos/%Y/%m/'),
        ),
    ]
