# Generated by Django 6.0.2 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garantias", "0004_alter_garantiaarchivo_archivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="garantia",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]

