# Generated by Django 6.0.2 on 2026-05-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garantias", "0005_garantia_fecha_vencimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garantia",
            name="cliente",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="garantias", to="clientes.cliente"),
        ),
        migrations.AlterField(
            model_name="garantia",
            name="prioridad",
            field=models.CharField(blank=True, choices=[("BAJA", "Baja"), ("MEDIA", "Media"), ("ALTA", "Alta")], default="MEDIA", max_length=20),
        ),
        migrations.AlterField(
            model_name="garantia",
            name="titulo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]

