# Generated by Django 6.0.2 on 2026-08-03 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0006_campos_opcionales_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#1D6F6F', max_length=7)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='garantia',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='garantia',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='garantias', to='garantias.garantiaetiqueta'),
        ),
    ]
