# Generated by Django 6.0.2 on 2026-08-04 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


COLUMNAS_INICIALES = (
    ("SOLICITUD_NAVIERA", "Solicitud a naviera"),
    ("EN_PROCESO", "En proceso"),
    ("PAGO_NAVIERA_ZAHA", "Pago naviera a zaha"),
    ("DEVOLUCION_CLIENTE", "Devolución a cliente"),
)


def crear_columnas_y_sincronizar(apps, schema_editor):
    Garantia = apps.get_model("garantias", "Garantia")
    GarantiaColumna = apps.get_model("garantias", "GarantiaColumna")

    columnas = {}
    for orden, (codigo, nombre) in enumerate(COLUMNAS_INICIALES, start=1):
        columna, _created = GarantiaColumna.objects.update_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "orden": orden,
                "activa": True,
            },
        )
        columnas[codigo] = columna.pk

    for codigo, columna_id in columnas.items():
        Garantia.objects.filter(estado=codigo, columna__isnull=True).update(
            columna_id=columna_id
        )


def revertir_columnas_iniciales(apps, schema_editor):
    GarantiaColumna = apps.get_model("garantias", "GarantiaColumna")
    GarantiaColumna.objects.filter(
        codigo__in=[codigo for codigo, _nombre in COLUMNAS_INICIALES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0007_garantiaetiqueta_alter_garantia_prioridad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_columnas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Columna de garantias',
                'verbose_name_plural': 'Columnas de garantias',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='garantia',
            name='columna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='garantias.garantiacolumna'),
        ),
        migrations.RunPython(
            crear_columnas_y_sincronizar,
            revertir_columnas_iniciales,
        ),
    ]
