# Generated by Django 6.0.2 on 2026-09-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0010_merge_en_proceso_into_solicitud_naviera'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
