# Generated by Django 6.0.2 on 2026-05-17 04:54

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_tipo_cliente_alter_cliente_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('info', 'Cyan'), ('secondary', 'Gris'), ('dark', 'Oscuro'), ('light', 'Claro')], default='primary', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendientes'), ('SEGUROS', 'Seguros'), ('PRUEBA_VALOR', 'Prueba de valor'), ('EN_ADUANA', 'En aduana'), ('TRANSITO_NACIONAL', 'Tránsito nacional'), ('COORDINAR_PICKUP', 'Por coordinar pickup'), ('TRANSITO_INTERNACIONAL', 'Tránsito internacional'), ('EXPEDIENTE_CG', 'Expediente CG'), ('SOLICITUD_CUENTA_GASTOS', 'Solicitud de cuenta gastos')], default='PENDIENTE', max_length=30)),
                ('prioridad', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignados', models.ManyToManyField(blank=True, related_name='operaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='operaciones', to='operaciones.operacionetiqueta')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='uploads'), upload_to='operaciones/archivos/%Y/%m/')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='operaciones.operacion')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperacionComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='operaciones.operacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperacionEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='operaciones.operacion')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
