# Generated by Django 6.0.2 on 2026-05-17 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='operacionetiqueta',
            name='color',
            field=models.CharField(default='#3E9FA2', help_text='Color en formato hexadecimal (ej: #3E9FA2)', max_length=7),
        ),
        migrations.AddField(
            model_name='operacion',
            name='opciones',
            field=models.ManyToManyField(blank=True, related_name='operaciones', to='operaciones.operacionopcion'),
        ),
    ]
