# Generated by Django 6.0.2 on 2026-07-22 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operacionopcion_alter_operacionetiqueta_color_and_more'),
        ('solicitudes', '0010_referencia_solicitud_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='referencia_origen',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacion_generada', to='solicitudes.referencia'),
        ),
    ]
