# Generated by Django 6.0.2 on 2026-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_operacion_referencia_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendientes'), ('SEGUROS', 'Seguros'), ('PRUEBA_VALOR', 'Prueba de valor'), ('EN_ADUANA', 'En aduana'), ('TRANSITO_NACIONAL', 'Tránsito nacional'), ('COORDINAR_PICKUP', 'Pick up'), ('TRANSITO_INTERNACIONAL', 'Tránsito internacional'), ('EXPEDIENTE_CG', 'Expediente CG'), ('SOLICITUD_CUENTA_GASTOS', 'Solicitud de cuenta gastos')], default='PENDIENTE', max_length=30),
        ),
    ]
