# Generated by Django 6.0.2 on 2026-08-04 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


COLUMNAS_INICIALES = (
    ("PENDIENTE", "Pendientes"),
    ("SEGUROS", "Seguros"),
    ("PRUEBA_VALOR", "Prueba de valor"),
    ("EN_ADUANA", "En aduana"),
    ("TRANSITO_NACIONAL", "Tránsito nacional"),
    ("COORDINAR_PICKUP", "Pick up"),
    ("TRANSITO_INTERNACIONAL", "Tránsito internacional"),
    ("EXPEDIENTE_CG", "Expediente CG"),
    ("SOLICITUD_CUENTA_GASTOS", "Solicitud de cuenta gastos"),
)


def crear_columnas_y_sincronizar(apps, schema_editor):
    Operacion = apps.get_model("operaciones", "Operacion")
    OperacionColumna = apps.get_model("operaciones", "OperacionColumna")

    columnas = {}
    for orden, (codigo, nombre) in enumerate(COLUMNAS_INICIALES, start=1):
        columna, _created = OperacionColumna.objects.update_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "orden": orden,
                "activa": True,
            },
        )
        columnas[codigo] = columna.pk

    for codigo, columna_id in columnas.items():
        Operacion.objects.filter(estado=codigo, columna__isnull=True).update(
            columna_id=columna_id
        )


def revertir_columnas_iniciales(apps, schema_editor):
    OperacionColumna = apps.get_model("operaciones", "OperacionColumna")
    OperacionColumna.objects.filter(
        codigo__in=[codigo for codigo, _nombre in COLUMNAS_INICIALES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_operacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_columnas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Columna de operaciones',
                'verbose_name_plural': 'Columnas de operaciones',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='operacion',
            name='columna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='operaciones.operacioncolumna'),
        ),
        migrations.RunPython(
            crear_columnas_y_sincronizar,
            revertir_columnas_iniciales,
        ),
    ]
