# Generated by Django 6.0.2 on 2026-08-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_operacion_eliminado_en_operacion_eliminado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionElementoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('completado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_accion', to='operaciones.operacion')),
            ],
            options={
                'verbose_name': 'Elemento de accion',
                'verbose_name_plural': 'Elementos de accion',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
