# Generated by Django 6.0.2 on 2026-08-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_operacionelementoaccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacion',
            options={'ordering': ['posicion', '-fecha_creacion', '-id']},
        ),
        migrations.AddField(
            model_name='operacion',
            name='carga_lista',
            field=models.DateField(blank=True, null=True, verbose_name='Carga lista'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='ETA'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='etd',
            field=models.DateField(blank=True, null=True, verbose_name='ETD'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='posicion',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
