# Generated by Django 6.0.2 on 2026-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_remove_operacion_carga_lista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='ETD'),
        ),
    ]
