# Generated by Django 6.0.2 on 2026-09-02 08:12

from django.db import migrations


def restore_fecha_vencimiento(apps, schema_editor):
    Operacion = apps.get_model('operaciones', 'Operacion')
    for operacion in Operacion.objects.filter(etd__isnull=False):
        operacion.fecha_vencimiento = operacion.etd
        operacion.save(update_fields=['fecha_vencimiento'])

def reverse_restore(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_operacion_fecha_vencimiento'),
    ]

    operations = [
        migrations.RunPython(restore_fecha_vencimiento, reverse_restore),
    ]
