# Generated by Django 6.0.2 on 2026-09-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_restore_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendientes'), ('REVALIDACIONES', 'Revalidaciones'), ('CONSULTORIA', 'Consultoria'), ('SEGUROS', 'Seguros'), ('PRUEBA_VALOR', 'MANIFESTACIÓN DE VALOR'), ('EN_ADUANA', 'En aduana'), ('TRANSITO_NACIONAL', 'Tránsito nacional'), ('COORDINAR_PICKUP', 'Pick up'), ('TRANSITO_INTERNACIONAL', 'Tránsito internacional'), ('EXPEDIENTE_CG', 'Expediente CG'), ('SOLICITUD_CUENTA_GASTOS', 'Solicitud de cuenta gastos')], default='PENDIENTE', max_length=30),
        ),
    ]
