# Generated by Django 6.0.2 on 2026-02-19 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('consecutivo', models.CharField(max_length=20, verbose_name='Consecutivo')),
                ('cliente', models.CharField(max_length=255, verbose_name='Prospecto de cliente')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100)),
                ('aerea', models.CharField(blank=True, max_length=100)),
                ('maritima', models.CharField(blank=True, max_length=100)),
                ('terrestre', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('agencia_aduanal', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('sg', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=255)),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('aerea', models.BooleanField(default=False)),
                ('maritima', models.BooleanField(default=False)),
                ('terrestre', models.BooleanField(default=False)),
                ('estado_aereo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_maritimo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_terrestre', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
