# Generated by Django 6.0.2 on 2026-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='referencia',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
