# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations


def _crear_perfiles_faltantes(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("solicitudes", "UserProfile")

    user_ids_con_perfil = set(UserProfile.objects.values_list("user_id", flat=True))
    perfiles_nuevos = [
        UserProfile(user_id=user_id, segundo_nombre="")
        for user_id in User.objects.values_list("id", flat=True)
        if user_id not in user_ids_con_perfil
    ]
    if perfiles_nuevos:
        UserProfile.objects.bulk_create(perfiles_nuevos, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0003_userprofile"),
    ]

    operations = [
        migrations.RunPython(_crear_perfiles_faltantes, migrations.RunPython.noop),
    ]

