# Generated by Django 6.0.2 on 2026-04-07 22:14

import re

from django.db import migrations, models
from django.db.models import Count


def _siguiente_codigo(prefijo, usados, ultimo):
    candidato = ultimo + 1
    while candidato in usados:
        candidato += 1
    usados.add(candidato)
    return candidato, candidato


def _resolver_duplicados_solicitud(apps, schema_editor):
    Solicitud = apps.get_model("solicitudes", "Solicitud")

    duplicados = (
        Solicitud.objects.values("sg")
        .annotate(cantidad=Count("id"))
        .filter(cantidad__gt=1)
    )

    cache_por_anio = {}

    for item in duplicados:
        sg_duplicado = item["sg"]
        filas = list(Solicitud.objects.filter(sg=sg_duplicado).order_by("id"))
        if len(filas) <= 1:
            continue

        for fila in filas[1:]:
            anio = int(getattr(fila, "anio", 0) or 0)
            prefijo = f"SG{str(anio)[-2:]}" if anio else "SG00"

            if anio not in cache_por_anio:
                patron = re.compile(rf"^{re.escape(prefijo)}(\d{{3}})$")
                usados = set()
                ultimo = 0
                for valor in Solicitud.objects.filter(sg__startswith=prefijo).values_list("sg", flat=True):
                    limpio = str(valor or "").strip().replace("-", "")
                    match = patron.match(limpio)
                    if match:
                        numero = int(match.group(1))
                        usados.add(numero)
                        ultimo = max(ultimo, numero)
                cache_por_anio[anio] = (prefijo, patron, usados, ultimo)

            prefijo, patron, usados, ultimo = cache_por_anio[anio]
            nuevo, ultimo = _siguiente_codigo(prefijo, usados, ultimo)
            cache_por_anio[anio] = (prefijo, patron, usados, ultimo)

            fila.sg = f"{prefijo}{nuevo:03d}"
            fila.save(update_fields=["sg"])


def _resolver_duplicados_cotizacion(apps, schema_editor):
    Cotizacion = apps.get_model("solicitudes", "Cotizacion")

    duplicados = (
        Cotizacion.objects.values("consecutivo")
        .annotate(cantidad=Count("id"))
        .filter(cantidad__gt=1)
    )

    cache_por_anio = {}

    for item in duplicados:
        consecutivo_duplicado = item["consecutivo"]
        filas = list(Cotizacion.objects.filter(consecutivo=consecutivo_duplicado).order_by("id"))
        if len(filas) <= 1:
            continue

        for fila in filas[1:]:
            anio = int(getattr(fila, "anio", 0) or 0)
            prefijo = f"C{str(anio)[-2:]}" if anio else "C00"

            if anio not in cache_por_anio:
                patron = re.compile(rf"^{re.escape(prefijo)}(\d{{3}})$")
                usados = set()
                ultimo = 0
                for valor in Cotizacion.objects.filter(consecutivo__startswith=prefijo).values_list("consecutivo", flat=True):
                    limpio = str(valor or "").strip().upper()
                    match = patron.match(limpio)
                    if match:
                        numero = int(match.group(1))
                        usados.add(numero)
                        ultimo = max(ultimo, numero)
                cache_por_anio[anio] = (prefijo, patron, usados, ultimo)

            prefijo, patron, usados, ultimo = cache_por_anio[anio]
            nuevo, ultimo = _siguiente_codigo(prefijo, usados, ultimo)
            cache_por_anio[anio] = (prefijo, patron, usados, ultimo)

            fila.consecutivo = f"{prefijo}{nuevo:03d}"
            fila.save(update_fields=["consecutivo"])


def _resolver_duplicados(apps, schema_editor):
    _resolver_duplicados_solicitud(apps, schema_editor)
    _resolver_duplicados_cotizacion(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_backfill_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.RunPython(_resolver_duplicados, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cotizacion',
            name='consecutivo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='sg',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
