# Generated by Django 6.0.2 on 2026-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_cotizacion_idempotency_key_solicitud_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_cumplido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
