# Generated by Django 6.0.2 on 2026-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitud_fecha_cumplido'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='medio_operacion',
            field=models.CharField(blank=True, choices=[('aerea', 'Aérea'), ('maritima', 'Marítima'), ('terrestre', 'Terrestre')], max_length=20, null=True),
        ),
    ]
