# Generated by Django 6.0.2 on 2026-04-10 20:25

from django.db import migrations, models


def _backfill_consecutivo(apps, schema_editor):
    Referencia = apps.get_model("solicitudes", "Referencia")
    rows = list(Referencia.objects.order_by("id").values_list("id", "consecutivo"))
    siguiente = 1
    for ref_id, consecutivo in rows:
        if consecutivo is not None:
            siguiente = max(siguiente, int(consecutivo) + 1)

    for ref_id, consecutivo in rows:
        if consecutivo is None:
            Referencia.objects.filter(id=ref_id).update(consecutivo=siguiente)
            siguiente += 1


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_referencia_medio_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_consecutivo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="referencia",
            name="consecutivo",
            field=models.IntegerField(db_index=True),
        ),
    ]
