# Generated by Django 6.0.3 on 2026-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_referencia_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cumplido', 'Cumplido'), ('Fuera de plazo', 'Fuera de plazo')], default='Pendiente', max_length=50),
        ),
    ]
