# Generated by Django 6.0.2 on 2026-07-22 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='solicitud_origen',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencia_generada', to='solicitudes.solicitud'),
        ),
    ]
