# Generated by Django 6.0.2 on 2026-09-23 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_referencia_panel_cotizacion_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='solicitudes.referencia')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_referencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
    ]
