# Generated by Django 6.0.3 on 2026-05-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=16)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='incidencias_estado_1b1ac6_idx'), models.Index(fields=['prioridad'], name='incidencias_priorid_c1fd4d_idx'), models.Index(fields=['responsable'], name='incidencias_respons_a3b4b1_idx'), models.Index(fields=['fecha_creacion'], name='incidencias_fecha_c_279105_idx')],
            },
        ),
    ]
