# Generated by Django on 2026-03-10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=150)),
                ("empresa", models.CharField(blank=True, max_length=150)),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("rfc", models.CharField(blank=True, max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("potencial", "Potencial"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                ("fecha_alta", models.DateField(default=django.utils.timezone.now)),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-fecha_alta", "nombre"],
            },
        ),
    ]
