# Generated by Django 6.0.2 on 2026-03-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_celular_cliente_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
