# Generated by Django 6.0.2 on 2026-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_tipo_cliente_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('nombre', 'empresa'), name='cliente_nombre_empresa_unicos'),
        ),
    ]
