# Generated by Django 6.0.2 on 2026-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_cliente_nombre_empresa_unicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuentas_por_cobrar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
