# Generated by Django 6.0.2 on 2026-09-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_consecutivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteconsecutivo',
            options={'verbose_name': 'Consecutivo de clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('existente', 'Existente')], default='nuevo', max_length=20),
        ),
    ]
